### PR TITLE
feat(artist): fix page display on small devices

### LINKED ISSUE #317: fix artist page display
image

### PR DESCRIPTION
**Pull request by Iqro-dev**
closes #317

### CODE REVIEW

File: app/(items)/artist/[artist-id]/page.tsx [hunk 1]
```diff
@@ -18,44 +20,81 @@ export default async function ArtistPage({ params }: ArtistPageProps) {
...
+                <div className="flex flex-row justify-between">
+                  <ButtonLink href={`/album/${id}`}>
+                    <span className="truncate w-[170px]">{name}</span>
+                  </ButtonLink>
+
+                  <SpotifyLink href={href} />
+                </div>
+
+                <div>
+                  {new Date(releaseDate).getFullYear()} &bull;{' '}
```
Comment (Mnigos) [inline app/(items)/artist/[artist-id]/page.tsx:91]:
```suggestion
                  {new Date(releaseDate).getFullYear()} &bull;&nbsp;
```

**Review by Mnigos — CHANGES_REQUESTED** [review]

File: app/(items)/artist/[artist-id]/page.tsx [hunk 2]
```diff
@@ -18,44 +20,88 @@ export default async function ArtistPage({ params }: ArtistPageProps) {
...
+                  <div className="flex flex-row justify-between">
+                    <ButtonLink href={`/album/${id}`}>
+                      <span className="truncate w-[170px]">{name}</span>
+                    </ButtonLink>
+
+                    <SpotifyLink href={href} />
+                  </div>
+
+                  <div>
+                    {new Date(releaseDate).getFullYear()} &bull;{' '}
```
Comment (Mnigos) [inline app/(items)/artist/[artist-id]/page.tsx:98]:
```suggestion
                    {new Date(releaseDate).getFullYear()} &bull;&nbsp;
```

**Review by Mnigos — CHANGES_REQUESTED** [review]
